/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.example --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 62a8449ba2cd6e2d84a3c7f208b1e2a5)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	DATABASE_URL: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_ALLOW_REGISTRATION: string;
	NEXT_PUBLIC_SENTRY_DSN: string;
	SENTRY_DSN: string;
	SENTRY_ORG: string;
	SENTRY_PROJECT: string;
	SENTRY_AUTH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/server");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "BETTER_AUTH_ALLOW_REGISTRATION" | "NEXT_PUBLIC_SENTRY_DSN" | "SENTRY_DSN" | "SENTRY_ORG" | "SENTRY_PROJECT" | "SENTRY_AUTH_TOKEN">> {}
}
