/* eslint-disable */
/* v8 ignore file */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as HistoryIdRouteImport } from './routes/history/$id'
import { Route as VodsIndexRouteImport } from './routes/vods/index'
import { Route as VodsIdRouteImport } from './routes/vods/$id'
import { Route as AdminContentIdRouteImport } from './routes/admin/content/$id'
import { Route as AdminContentNewRouteImport } from './routes/admin/content/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as VodsIdSessionRouteImport } from './routes/vods/$id.session'
import { Route as ApiVodsIdManifestRouteImport } from './routes/api/vods/$id/manifest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/demo.lazy').then((d) => d.Route))
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/audit.lazy').then((d) => d.Route))
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/content.lazy').then((d) => d.Route))
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/users.lazy').then((d) => d.Route))
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/history/index.lazy').then((d) => d.Route))
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/history/$id.lazy').then((d) => d.Route))
const VodsIndexRoute = VodsIndexRouteImport.update({
  id: '/vods/',
  path: '/vods/',
  getParentRoute: () => rootRouteImport,
} as any)
const VodsIdRoute = VodsIdRouteImport.update({
  id: '/vods/$id',
  path: '/vods/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentIdRoute = AdminContentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminContentRoute,
} as any).lazy(() =>
  import('./routes/admin/content/$id.lazy').then((d) => d.Route),
)
const AdminContentNewRoute = AdminContentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminContentRoute,
} as any).lazy(() =>
  import('./routes/admin/content/new.lazy').then((d) => d.Route),
)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VodsIdSessionRoute = VodsIdSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => VodsIdRoute,
} as any).lazy(() =>
  import('./routes/vods/$id.session.lazy').then((d) => d.Route),
)
const ApiVodsIdManifestRoute = ApiVodsIdManifestRouteImport.update({
  id: '/api/vods/$id/manifest',
  path: '/api/vods/$id/manifest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/history/$id': typeof HistoryIdRoute
  '/vods/$id': typeof VodsIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/vods/': typeof VodsIndexRoute
  '/admin/content/$id': typeof AdminContentIdRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/vods/$id/session': typeof VodsIdSessionRoute
  '/api/vods/$id/manifest': typeof ApiVodsIdManifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/history/$id': typeof HistoryIdRoute
  '/vods/$id': typeof VodsIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/history': typeof HistoryIndexRoute
  '/vods': typeof VodsIndexRoute
  '/admin/content/$id': typeof AdminContentIdRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/vods/$id/session': typeof VodsIdSessionRoute
  '/api/vods/$id/manifest': typeof ApiVodsIdManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/history/$id': typeof HistoryIdRoute
  '/vods/$id': typeof VodsIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/vods/': typeof VodsIndexRoute
  '/admin/content/$id': typeof AdminContentIdRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/vods/$id/session': typeof VodsIdSessionRoute
  '/api/vods/$id/manifest': typeof ApiVodsIdManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/demo'
    | '/privacy'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/users'
    | '/history/$id'
    | '/vods/$id'
    | '/admin/'
    | '/history/'
    | '/vods/'
    | '/admin/content/$id'
    | '/admin/content/new'
    | '/api/auth/$'
    | '/api/media/$'
    | '/vods/$id/session'
    | '/api/vods/$id/manifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/privacy'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/users'
    | '/history/$id'
    | '/vods/$id'
    | '/admin'
    | '/history'
    | '/vods'
    | '/admin/content/$id'
    | '/admin/content/new'
    | '/api/auth/$'
    | '/api/media/$'
    | '/vods/$id/session'
    | '/api/vods/$id/manifest'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/demo'
    | '/privacy'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/users'
    | '/history/$id'
    | '/vods/$id'
    | '/admin/'
    | '/history/'
    | '/vods/'
    | '/admin/content/$id'
    | '/admin/content/new'
    | '/api/auth/$'
    | '/api/media/$'
    | '/vods/$id/session'
    | '/api/vods/$id/manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DemoRoute: typeof DemoRoute
  PrivacyRoute: typeof PrivacyRoute
  HistoryIdRoute: typeof HistoryIdRoute
  VodsIdRoute: typeof VodsIdRouteWithChildren
  HistoryIndexRoute: typeof HistoryIndexRoute
  VodsIndexRoute: typeof VodsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  ApiVodsIdManifestRoute: typeof ApiVodsIdManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods/': {
      id: '/vods/'
      path: '/vods'
      fullPath: '/vods/'
      preLoaderRoute: typeof VodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods/$id': {
      id: '/vods/$id'
      path: '/vods/$id'
      fullPath: '/vods/$id'
      preLoaderRoute: typeof VodsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/$id': {
      id: '/admin/content/$id'
      path: '/$id'
      fullPath: '/admin/content/$id'
      preLoaderRoute: typeof AdminContentIdRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/new': {
      id: '/admin/content/new'
      path: '/new'
      fullPath: '/admin/content/new'
      preLoaderRoute: typeof AdminContentNewRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods/$id/session': {
      id: '/vods/$id/session'
      path: '/session'
      fullPath: '/vods/$id/session'
      preLoaderRoute: typeof VodsIdSessionRouteImport
      parentRoute: typeof VodsIdRoute
    }
    '/api/vods/$id/manifest': {
      id: '/api/vods/$id/manifest'
      path: '/api/vods/$id/manifest'
      fullPath: '/api/vods/$id/manifest'
      preLoaderRoute: typeof ApiVodsIdManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminContentRouteChildren {
  AdminContentIdRoute: typeof AdminContentIdRoute
  AdminContentNewRoute: typeof AdminContentNewRoute
}

const AdminContentRouteChildren: AdminContentRouteChildren = {
  AdminContentIdRoute: AdminContentIdRoute,
  AdminContentNewRoute: AdminContentNewRoute,
}

const AdminContentRouteWithChildren = AdminContentRoute._addFileChildren(
  AdminContentRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContentRoute: typeof AdminContentRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminContentRoute: AdminContentRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VodsIdRouteChildren {
  VodsIdSessionRoute: typeof VodsIdSessionRoute
}

const VodsIdRouteChildren: VodsIdRouteChildren = {
  VodsIdSessionRoute: VodsIdSessionRoute,
}

const VodsIdRouteWithChildren =
  VodsIdRoute._addFileChildren(VodsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DemoRoute: DemoRoute,
  PrivacyRoute: PrivacyRoute,
  HistoryIdRoute: HistoryIdRoute,
  VodsIdRoute: VodsIdRouteWithChildren,
  HistoryIndexRoute: HistoryIndexRoute,
  VodsIndexRoute: VodsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  ApiVodsIdManifestRoute: ApiVodsIdManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
